import React from 'react';
import { CheckOutlined } from '@ant-design/icons';
import { NavLink } from 'react-router-dom';

const Home = () => {
    return (
        <div className='home-p'>
            <div className="container">
                <div className="row" >
                    <div className="col" style={{ marginTop: 140 }}>
                        <h1><strong>IMPRESSIVE CV</strong> EASY ONLINE BUILDER</h1><br /><br />
                        <h5 className='text-center'><CheckOutlined style={{ fontSize: 30, color: 'red' }} /> Professional out-of-the-box resumes, instantly generated by the most advanced resume builder technology available.</h5><br></br>
                        <h5 className='text-center'><CheckOutlined style={{ fontSize: 30, color: 'red' }} />Effortless crafting. Real-time preview & pre-written resume examples. Dozens of HR-approved resume templates.</h5><br></br>
                        <h5 className='text-center'><CheckOutlined style={{ fontSize: 30, color: 'red' }} /> Land your dream job with the perfect resume employers are looking for!</h5><br></br>
                        <NavLink to='/choose_template'><button className="btn home-btn" type="submit">Create my CV </button></NavLink>
                    </div>
                    <div className="col"><img src="https://www.designbolts.com/wp-content/uploads/2018/10/Free-Professional-Resume-Template-in-DOC-PSD-Ai-Format-3.jpg" className='home-img' /> </div>
                </div>
            </div><br /><br /><br />
            <div className='examples-body'>
                <h3 className='text-center'>3 EASY STEPS TO CREATE YOUR PERFECT CV</h3><hr />
                <div className="container">
                    <div className="row">
                        <div className="col">
                            <img src="https://cdn3.iconfinder.com/data/icons/business-102/512/paper.png" className='home-icon' />
                            <h5 className='text-center'><strong>CHOOSE YOUR TEMPLATE</strong></h5>
                            <p>Our professional resume templates are designed strictly following all industry guidelines and best practices </p>
                        </div>
                        <div className="col">
                            <img src="https://vivefitness.com/wp-content/uploads/2020/07/memberships.png" className='home-icon' />
                            <h5 className='text-center'><strong>SHOW WHAT YOU'RE MADE OF</strong></h5>
                            <p>Not finding the right words to showcase yourself? We´ve added thousands of pre-written examples and resume samples.</p>
                        </div>
                        <div className="col">
                            <img src="https://9clouds.com/wp-content/uploads/2019/01/9-Clouds-Manifesto-Icon2.png" className='home-icon' />
                            <h5 className='text-center'><strong>DOWNLOAD YOUR CV</strong></h5>
                            <p>Start impressing employers. Download your awesome resume and land the job you are looking for, effortlessly.  </p>
                        </div>
                    </div>
                </div>
            </div><br /><br />
            <div className="container">
                <div className="row">
                    <div className="col col-3"></div>
                    <div className="col col-6">
                        <h3 className='text-center'><strong>PROFESSIONAL&nbsp; CV &nbsp;TEMPLATES</strong></h3><br />
                        <h6 className='text-center'>Choose from 20+ tailored-built templates that have landed thousands of people like you the jobs they were dreaming of.</h6><hr />
                    </div>
                    <div className="col col-3"></div>
                </div>
                <div className="row ">
                    <div id="carouselExampleIndicators" className="carousel slide" data-bs-ride="carousel">
                        <div className="carousel-indicators">
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" className="active" aria-current="true" aria-label="Slide 1"></button>
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 3"></button>
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 4"></button>
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="5" aria-label="Slide 5"></button>
                        </div>
                        <div className="carousel-inner">
                            <div className="carousel-item active">
                                <NavLink to='/choose_template'><img src="https://resumebuild.com/wp-content/uploads/2018/12/carousel_cv20.jpg" className="d-block carousel-img" alt="..." /></NavLink>
                            </div>
                            <div className="carousel-item">
                                <NavLink to='/choose_template'><img src="https://resumebuild.com/wp-content/uploads/2018/12/carousel_cv14.jpg" className="d-block carousel-img" alt="..." /></NavLink>
                            </div>
                            <div className="carousel-item">
                                <NavLink to='/choose_template'><img src="https://resumebuild.com/wp-content/uploads/2018/12/carousel_cv6.jpg" className="d-block carousel-img" alt="..." /></NavLink>
                            </div>
                            <div className="carousel-item">
                                <NavLink to='/choose_template'><img src="https://resumebuild.com/wp-content/uploads/2018/12/carousel_cv5.jpg" className="d-block carousel-img" alt="..." /></NavLink>
                            </div>
                            <div className="carousel-item">
                                <NavLink to='/choose_template'><img src="https://resumebuild.com/wp-content/uploads/2018/12/carousel_cv1.jpg" className="d-block carousel-img" alt="..." /></NavLink>
                            </div>
                            <div className="carousel-item">
                                <NavLink to='/choose_template'><img src="https://resumebuild.com/wp-content/uploads/2018/12/carousel_cv19.jpg" className="d-block carousel-img" alt="..." /></NavLink>
                            </div>
                        </div>
                        <button className="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                            <span className="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span className="visually-hidden">Previous</span>
                        </button>
                        <button className="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                            <span className="carousel-control-next-icon" aria-hidden="true"></span>
                            <span className="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Home